spring.application.name=YogaVibe
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/YogaVibe
spring.datasource.username=postgres
spring.datasource.password=542910

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
